version: '3.8'

services:
  web:
    image: "kasramp/metasearch:${IMAGE_TAG:-latest}"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      STANDARD_EBOOKS_TOKEN: ${STANDARD_EBOOKS_TOKEN}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8282:8080"
    networks:
      - shared-network
      - docker_gwbridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

networks:
  shared-network:
    external: true
  docker_gwbridge: