CREATE TABLE IF NOT EXISTS book (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    cover_image_url VARCHAR(2048) DEFAULT NULL,
    epub_url VARCHAR(2048) DEFAULT NULL,
    kobo_url VARCHAR(2048) DEFAULT NULL,
    mobi_url VARCHAR(2048) DEFAULT NULL,
    azw_url VARCHAR(2048) DEFAULT NULL,
    html_url VARCHAR(2048) DEFAULT NULL,
    provider VARCHAR(128) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_book_title ON book (title);
CREATE INDEX idx_book_author ON book (author);
CREATE INDEX idx_book_provider ON book (provider);