name: Build
on:
  pull_request:
    branches:
      - master
  # TODO remove once deployment script is added
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew build --no-daemon